### PR TITLE
Fix typo

### PR DESCRIPTION
**Pull request by goetas**
Hi I believe there is a typo here

### CODE REVIEW

**Comment by chrisguitarguy** [comment]
oh, a very nice latent bug. Would you be willing to add a test to verify that this is fixed?

The [current tests](https://github.com/chrisguitarguy/RequestIdBundle/blob/a59749fc94dc94bd58d343d1133af155507acec9/test/unit/EventListener/RequestIdListenerTest.php#L187-L188) use the same header for both request and response, which is why this bug wasn't caught.

**Comment by goetas** [comment]
Done.

I have also added https://github.com/chrisguitarguy/RequestIdBundle/pull/7/commits/f64710cde1a6926bc67ae177a3c8c4cf9099d702 that will fix partially https://github.com/chrisguitarguy/RequestIdBundle/issues/4 allowing flex to generate automatically the entry in bundles.php

**Comment by goetas** [comment]
Hi, any news on this? Are you fine with my changes?

**Comment by chrisguitarguy** [comment]
Hey, just haven't had a chance to get back to it yet. I'll be able to take a look tomorrow. Thanks!

**Review by chrisguitarguy — APPROVED** [review]

**Comment by goetas** [comment]
Thanks! 

Any chance to have 3.0.1 tagged?

**Comment by chrisguitarguy** [comment]
yep! https://github.com/chrisguitarguy/RequestIdBundle/releases/tag/3.0.1

**Comment by goetas** [comment]
Great, thanks a lot

**Pull request merged**
