### PR TITLE
Symfony 5 compatibility

### PR DESCRIPTION
**Pull request by smoench**
I had to remove Symfony 3.4 compatibility as the HttpKernel Event classes has been renamed.

### CODE REVIEW

**Review by goetas — APPROVED** [review]

**Comment by lunetics** [comment]
lovely

**Review by chrisguitarguy — APPROVED** [review]
Thank you!

**Comment by chrisguitarguy** [comment]
I'm going to tag a 4.0 RC for this -- I know you can _technically_ do dependency bumps in a minor version but that never sits right with me.

**Comment by smoench** [comment]
Thank you, @chrisguitarguy!

**Pull request merged**
